# Generated by Django 4.1.7 on 2023-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('E_coal', models.IntegerField()),
                ('E_hydro', models.IntegerField()),
                ('E_nuclear', models.IntegerField()),
                ('E_petroleum', models.IntegerField()),
                ('E_wind', models.IntegerField()),
                ('E_others', models.IntegerField()),
            ],
        ),
    ]
