# Generated by Django 4.1.7 on 2023-03-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('electrical_machine', models.IntegerField()),
                ('medical_precision_instruments', models.IntegerField()),
                ('radio_television', models.IntegerField()),
                ('rental_equipment', models.IntegerField()),
                ('others', models.IntegerField()),
                ('office_computers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('education_facility', models.IntegerField()),
                ('food_sale_facility', models.IntegerField()),
                ('healthcare_facility', models.IntegerField()),
                ('lodging_facility', models.IntegerField()),
                ('manufacturing_facility', models.IntegerField()),
                ('office_facility', models.IntegerField()),
                ('other_facility', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fugitive_gases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('purchased_steam', models.IntegerField()),
                ('domestic_heating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('blast_furnace_gas', models.IntegerField()),
                ('coke_ovens_gas', models.IntegerField()),
                ('gas_works_gas', models.IntegerField()),
                ('natural_gas', models.IntegerField()),
                ('diesel_oil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('residental_maintainance', models.IntegerField()),
                ('non_residential_maintainance', models.IntegerField()),
                ('hotel_and_retaurant_service', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('pipeline_transport', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('private_household_goods', models.IntegerField()),
                ('beverages', models.IntegerField()),
                ('dairy_products', models.IntegerField()),
                ('fish_products', models.IntegerField()),
                ('other_food_products', models.IntegerField()),
                ('furniture', models.IntegerField()),
                ('leather_goods', models.IntegerField()),
                ('meat_goods', models.IntegerField()),
                ('processed_rice', models.IntegerField()),
                ('sugar_products', models.IntegerField()),
                ('vegetable_oil', models.IntegerField()),
                ('wearing_apparel', models.IntegerField()),
                ('retail_trade', models.IntegerField()),
                ('retail_trade_others', models.IntegerField()),
                ('paper_products', models.IntegerField()),
                ('textile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('warehouse', models.IntegerField()),
                ('upstream_transportation', models.IntegerField()),
                ('air_freight', models.IntegerField()),
                ('water_freight', models.IntegerField()),
                ('rail', models.IntegerField()),
                ('inland_transportation', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('diesel_distance', models.IntegerField()),
                ('gasoline_distance', models.IntegerField()),
                ('electric_distance', models.IntegerField()),
                ('cng_distance', models.IntegerField()),
                ('lpg_distance', models.IntegerField()),
                ('bus_distance', models.IntegerField()),
                ('business_taxi_distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('water_supply', models.IntegerField()),
                ('water_treatment', models.IntegerField()),
                ('collected_and_purified_water', models.IntegerField()),
            ],
        ),
    ]
