# Generated by Django 4.1.5 on 2023-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbon_emmission',
            name='purchased_cooling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbon_emmission',
            name='purchased_heating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comp_database',
            name='purchased_cooling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comp_database',
            name='purchased_heating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comp_database',
            name='traditional_hydro_location',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('UK', 'Europe'), ('Africa', 'Africa'), ('LatinAmerica', 'LatinAmerica'), ('MiddleEast', 'MiddleEast'), ('OtherCountry', 'OtherCountry')], default='USA', max_length=100),
        ),
    ]
