# Generated by Django 4.1.7 on 2023-03-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimal', '0002_carbon_emmission_purchased_cooling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp_database',
            name='FerryInCar',
        ),
        migrations.RemoveField(
            model_name='comp_database',
            name='FerryOnFoot',
        ),
    ]
